services:  
  mfp:
    build: https://github.com/mhdzumair/mediaflow-proxy.git#main
    container_name: mfp
    restart: unless-stopped
    ports: 8080
      - 
    environment:
      API_PASSWORD: mfp
      FORWARDED_ALLOW_IPS: "*"
